module.exports = {
  update: "__New bot's version is here!__\n### Version 0.0.0 - Initial Release 🛠️\n- **Basic bot setup** with essential commands.\n- Integrated **voice channel functionality** for playing radio.\n- Added **AFK management** and **status updates**.\n- Configurable **.env file** for easy setup.\n- Initial **database options**: JSON, MySQL, MongoDB.",
  footer: {
    footerIcon: "https://cdn.discordapp.com/avatars/865630940361785345/d0c85fbbdb0ee9f105336a041904e7d8.png?size=4096",
    footerText: "©️ Persian Caesar"
  },
  color: {
    theme: "#2FB1FA",
    none: "#2B2D31",
    red: "#ff4d4d",
    green: "#ddcc33",
    uptime: "#51ff23",
    purpledark: "#6a006a",
    purplemedium: "#a958a5",
    purplelight: "#c481fb",
    orange: "#F9A72D",
    gold: "#daa520",
    reddark: "#8e2430",
    redlight: "#ff0000",
    bluedark: "#3b5998",
    cyan: "#5780cd",
    bluelight: "#ace9e7",
    aqua: "#33a1ee",
    pink: "#ff9dbb",
    greendark: "#2ac075",
    greenlight: "#a1ee33",
    white: "#f9f9f6",
    cream: "#ffdab9",
    blue: "#4c8bf5",
    yellow: "#E9E95A",
    purple: "#B05AE9",
    black: "#171717"
  },
  emotes: {
    default: {
      x: "❌",
      error: "⚠️",
      heartbeat: "💓",
      timer: "⏱️",
      multipleMusicalNotes: "🎶",
      admins: "💻",
      misc: "🔍",
      music: "🎧",
      clock: "⏰",
      badage: "📛",
      entry: "⛔",
      success: "☑",
      trash: "🪣",
      ticket: "🎟",
      tick: "✅",
      open: "🔓",
      close: "🔒",
      rename: "🖋",
      report: "📞",
      setup: "📝",
      reason: "📖",
      system: "⚙",
      hamer: "🔨",
      setting: "🛠",
      mail: "✉",
      type: "⌨",
      option: "🗄",
      log: "🪵",
      add: "📥",
      invite: "💌",
      help: "🧰",
      info: "📁",
      print: "🖨",
      plus: "➕",
      hurt: "💕",
      admin: "📠",
      category: "📂",
      claim: "🛄",
      premium: "💎",
      home: "🏡",
      ping: "🏓",
      typing: "👩🏻‍💻",
      learn: "📚",
      next: "⏭",
      update: "📡",
      left: "💨",
      join: "🚶🏻‍♀️",
      on: "🔛",
      off: "📴",
      disable1: "📴",
      disable2: "",
      enable1: "📱",
      enable2: "",
      server: "🔌",
      uptime: "⏳",
      users: "👥",
      cpu: "🖥",
      version: "🇻",
      memory: "💾",
      commands: "⌨",
      topgg: "🔝",
      reply: "➡",
      arrow_down: "👇🏻",
      arrow_right: "👉🏻",
      arrow_left: "👈🏻",
      down: "👉🏻",
      tickets: "🎫",
      owner: "👑",
      date: "📅",
      globe: "🌐",
      prohibited: "🚫"
    },
    theme: {}
  }
}
/**
 * @copyright
 * Code by Sobhan-SRZA (mr.sinre) | https://github.com/Sobhan-SRZA
 * Developed for Persian Caesar | https://github.com/Persian-Caesar | https://dsc.gg/persian-caesar
 *
 * If you encounter any issues or need assistance with this code,
 * please make sure to credit "Persian Caesar" in your documentation or communications.
 */
